# default setting
markdown: kramdown
highlighter: null

# plugins used
plugins:
  - jekyll-sitemap

# ignore gulp and stuff
exclude: ["node_modules", "gulpfile.js", "package.json", "bower_components", "gulp"]

buildtype: production
url: http://1934.nu
